### ISSUE TITLE
bosh deploy: Could not reserve network for package compilation: capacity

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-lite#255]
I have had concourse running on bosh-lite over the last couple days. Last night I rebuilt it and I got a compilation error "Could not reserve network for package compilation: capacity"

I tried again and it failed. I waited until the morning, created it again and it failed.

The commands I am running to reproduce:

```
vagrant up --provider=aws
vagrant ssh -c 'sudo iptables -t nat -A PREROUTING -p tcp -d $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --dport 8080 -j DNAT --to 10.244.8.2:8080'

bosh target 23.22.147.137 us-east-1
bosh upload release https://bosh.io/d/github.com/concourse/concourse
bosh upload release https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release
bosh upload stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent
curl -L -o concourse.yml https://raw.githubusercontent.com/concourse/concourse/develop/manifests/bosh-lite.yml
bosh deployment concourse.yml
bosh -n deploy
```

Gives me the output:

```
Processing deployment manifest
------------------------------
Getting deployment properties from director...
Unable to get properties list from director, trying without it...
Compiling deployment manifest...
Cannot get current deployment information from director, possibly a new deployment

Deploying
---------
Deployment name: `concourse.yml'
Director name: `Bosh Lite Director'

Director task 4
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:05)
  Started preparing deployment > Binding releases. Done (00:00:05)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:06)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:13)
  Started preparing deployment > Binding instance networks. Done (00:00:00)
     Done preparing deployment (00:00:29)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > bosh_deployment_resource/86c173a276e78a3f8b7458ed275bd53596b313ac
  Started compiling packages > bosh_io_release_resource/963ee9cd703fbf35302278c789d3311799d9617a
  Started compiling packages > bosh_io_stemcell_resource/27625ff4c39126a3286d4657abcde5955f1e6f94
   Failed compiling packages > bosh_deployment_resource/86c173a276e78a3f8b7458ed275bd53596b313ac: Could not reserve network for package compilation: capacity (00:00:00)
   Failed compiling packages > bosh_io_stemcell_resource/27625ff4c39126a3286d4657abcde5955f1e6f94: Could not reserve network for package compilation: capacity (00:00:00)
     Done compiling packages > bosh_io_release_resource/963ee9cd703fbf35302278c789d3311799d9617a (00:00:37)

Error 430001: Could not reserve network for package compilation: capacity

Task 4 error
```

Suggestions on how to debug? Thoughts on root cause?

**Comment by drnic** [comment]
@cppforlife ^ bot didn't pick this issue up

**Comment by drnic** [comment]
So weird - I can deploy a simple redis cluster on the same bosh-lite as expected.

**Comment by drnic** [comment]
I tried this on vagrant/vbox and the same error. I'm so confused! Why could this happen?

```
   Failed compiling packages > bosh_deployment_resource/86c173a276e78a3f8b7458ed275bd53596b313ac: Could not reserve network for package compilation: capacity (00:00:00)
   Failed compiling packages > bosh_io_release_resource/963ee9cd703fbf35302278c789d3311799d9617a: Could not reserve network for package compilation: capacity (00:00:00)
```

The concourse.yml manifest being used for all deployments is at https://gist.github.com/drnic/9e871d3c2363d84adab0

**Comment by drnic** [comment]
From bosh https://github.com/cloudfoundry/bosh/blob/develop/bosh-director/lib/bosh/director/network_reservation.rb#L108-L112 infers the `capacity` error relates to asking for dynamic IPs. But there are many dynamic IPs in the networking section of the manifest:

```
networks:
  - name: concourse
    subnets:
      # network with static ip used for web
      - range: 10.244.8.0/30
        reserved: [10.244.8.1]
        static: [10.244.8.2]
        cloud_properties: {}

      # networks for dynamic ips (db, workers, compilation vms)
      - range: 10.244.8.4/30
        reserved: [10.244.8.5]
        cloud_properties: {}
      - range: 10.244.8.8/30
        reserved: [10.244.8.9]
        cloud_properties: {}
      - range: 10.244.8.12/30
        reserved: [10.244.8.13]
        cloud_properties: {}
      - range: 10.244.8.16/30
        reserved: [10.244.8.17]
        cloud_properties: {}
      - range: 10.244.8.20/30
        reserved: [10.244.8.21]
        cloud_properties: {}
```
